-- ============================================================================
--  MEDIBOT — Historial del asistente
-- ============================================================================
--
--  QUE HACE ESTO
--  -------------
--  Guarda la conversacion con el asistente de quien haya iniciado sesion, para
--  que la encuentre igual desde el telefono y desde la computadora.
--
--  Sin sesion no se guarda nada aqui: el historial del visitante anonimo vive en
--  el `localStorage` de su propio navegador (`src/lib/historial.ts`). Esa
--  diferencia es intencional -- no hay forma de identificar a alguien que no ha
--  entrado, y crear filas atadas a una cookie seria acumular conversaciones de
--  desconocidos sin poder devolverselas ni borrarlas a peticion.
--
--  DONDE VIVE LA SEGURIDAD DE VERDAD
--  ---------------------------------
--  Igual que en 0001: aqui, no en React. La `anon key` viaja dentro del bundle
--  que descarga cualquier visitante, asi que cualquiera puede llamar a esta API a
--  mano. Lo unico que impide que una persona lea las conversaciones de otra son
--  las politicas de este fichero.
--
--  Esto es mas delicado que el foro. Una publicacion del foro es publica por
--  definicion; una conversacion con el asistente no lo es de ninguna manera. Por
--  eso aqui NO hay ninguna politica de lectura publica: ni siquiera para usuarios
--  verificados. Cada quien ve lo suyo y nada mas.
--
--  COMO APLICARLO
--  --------------
--    Panel de Supabase -> SQL Editor -> pegar este fichero -> Run
--
--  Es idempotente: se puede volver a ejecutar sin romper nada.
--
--  QUE PASA SI NO SE APLICA
--  ------------------------
--  El chat sigue funcionando. Quien inicie sesion tendra el historial en su
--  navegador, como los anonimos, y no entre dispositivos. No hay pantalla roja:
--  el codigo trata el fallo de esta tabla como "no hay historial remoto".
-- ============================================================================

-- ---------------------------------------------------------------------------
--  1. LA TABLA
-- ---------------------------------------------------------------------------
create table if not exists public.chat_mensajes (
  id         bigint generated by default as identity primary key,

  -- `on delete cascade`: si alguien borra su cuenta, sus conversaciones se van
  -- con ella. Es lo que corresponde con datos que solo le pertenecen a el.
  usuario_id uuid        not null references auth.users (id) on delete cascade,

  -- Los mismos dos valores que usa el codigo (`src/lib/chat.ts`). El CHECK evita
  -- que entre un rol inventado desde una llamada a mano a la API: sin el, alguien
  -- podria insertar rol 'system' y colar instrucciones en el prompt del modelo.
  rol        text        not null check (rol in ('usuario', 'bot')),

  -- El tope coincide con MAX_CARACTERES_MENSAJE del Worker. Aqui no es una
  -- comodidad, es un limite: sin el, cualquiera con la anon key podria llenar la
  -- base de datos escribiendo mensajes de megabytes.
  texto      text        not null check (length(texto) between 1 and 1000),

  creado_en  timestamptz not null default now()
);

-- El unico patron de consulta que existe: "dame mis mensajes en orden".
create index if not exists idx_chat_usuario
  on public.chat_mensajes (usuario_id, creado_en);

-- ---------------------------------------------------------------------------
--  2. CONTROL DE ACCESO
-- ---------------------------------------------------------------------------
alter table public.chat_mensajes enable row level security;

drop policy if exists chat_leer_propio     on public.chat_mensajes;
drop policy if exists chat_crear_propio    on public.chat_mensajes;
drop policy if exists chat_borrar_propio   on public.chat_mensajes;

--  Leer: solo lo tuyo. No hay excepcion para nadie.
create policy chat_leer_propio on public.chat_mensajes
  for select
  using (auth.uid() = usuario_id);

--  Crear: solo a tu nombre.
--
--  `with check` y no `using`: en un INSERT no hay fila previa que comprobar, hay
--  que validar la que entra. Sin esto, alguien podria insertar mensajes en la
--  conversacion de otra persona -- y como el asistente reenvia el historial al
--  modelo, seria una via para meterle texto a la conversacion de un tercero.
create policy chat_crear_propio on public.chat_mensajes
  for insert
  with check (auth.uid() = usuario_id);

--  Borrar: solo lo tuyo. Es lo que usa el boton de "empezar de nuevo".
create policy chat_borrar_propio on public.chat_mensajes
  for delete
  using (auth.uid() = usuario_id);

--  No hay politica de UPDATE, y es a proposito: un mensaje ya dicho no se edita.
--  Sin politica, RLS lo deniega por defecto.

-- ---------------------------------------------------------------------------
--  3. PODA AUTOMATICA
-- ---------------------------------------------------------------------------
--  Deja solo los ultimos 100 mensajes de cada persona.
--
--  POR QUE UN TRIGGER Y NO CODIGO EN REACT
--  ---------------------------------------
--  Porque el limite tiene que aguantar aunque nadie lo pida. Si la poda viviera
--  en el cliente, bastaria con no ejecutarla -- o con llamar a la API a mano --
--  para que una cuenta creciera sin freno. Aqui se aplica sola en cada insercion.
--
--  100 y no 40 (lo que guarda el navegador): el espacio en la base de datos no es
--  el del navegador, y tener mas historial del que se puede leer no molesta.
create or replace function public.podar_chat()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.chat_mensajes
  where id in (
    select id from public.chat_mensajes
    where usuario_id = new.usuario_id
    order by creado_en desc, id desc
    offset 100
  );
  return null;  -- trigger AFTER: el valor de retorno se ignora
end;
$$;

drop trigger if exists trg_podar_chat on public.chat_mensajes;

create trigger trg_podar_chat
  after insert on public.chat_mensajes
  for each row
  execute function public.podar_chat();

-- ---------------------------------------------------------------------------
--  4. COMPROBACION
-- ---------------------------------------------------------------------------
--  Al terminar deberia decir que RLS esta activo y que hay 3 politicas.
--  Si dice 0 politicas, algo fallo y la tabla NO tiene control de acceso.
do $$
declare
  n_politicas int;
  rls_activo  boolean;
begin
  select count(*) into n_politicas
  from pg_policies
  where schemaname = 'public' and tablename = 'chat_mensajes';

  select relrowsecurity into rls_activo
  from pg_class where oid = 'public.chat_mensajes'::regclass;

  raise notice 'chat_mensajes: RLS=% politicas=%', rls_activo, n_politicas;

  if not rls_activo or n_politicas < 3 then
    raise exception 'El historial del chat quedo sin control de acceso (RLS=% politicas=%)',
      rls_activo, n_politicas;
  end if;
end $$;
